# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
---
meta:
  name:     (( param "Please name your pipeline" ))
  pipeline: (( grab meta.name ))
  target:   "am"

  git:
    email:  "<>"
    name:   "CI Bot"

  docker:
    registry: am-registry:5000
    image_prefix: (( concat meta.docker.registry "/anothermemory/" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        "anothermemory"
    repo:         (( param "Please specify the name of the Github repository" ))
    private_key:  ((git_private_key))
    access_token: ((git_access_token))

  resource:
    git:
      type: git
      check_every: 15s
      source:
        uri: (( grab meta.github.uri ))
        private_key: (( grab meta.github.private_key ))
        branch: master
    dockerimage:
      base:
        type: docker-image
        check_every: 15s
        source:
          tag: master
          insecure_registries: [ (( grab meta.docker.registry )) ]
      go-base:
        .: (( inject meta.resource.dockerimage.base ))
        source: { repository: (( concat meta.docker.image_prefix "go-base" )) }
      go-vendor:
        .: (( inject meta.resource.dockerimage.base ))
        source: { repository: (( concat meta.docker.image_prefix "go-vendor" )) }

resources:
- name: git-develop
  .: (( inject meta.resource.git ))
  source: { branch: develop}

- name: git-master
  .: (( inject meta.resource.git ))

- name: docker-image-go-base-develop
  .: (( inject meta.resource.dockerimage.go-base ))
  source: { tag: develop}

- name: docker-image-go-base-master
  .: (( inject meta.resource.dockerimage.go-base ))

- name: docker-image-go-vendor-develop
  .: (( inject meta.resource.dockerimage.go-vendor ))
  source: { tag: develop}

- name: docker-image-go-vendor-master
  .: (( inject meta.resource.dockerimage.go-vendor ))

jobs:
- name: build-go-vendor-develop
  serial: true
  plan:
  - aggregate:
    - { get: docker-image-go-base-develop, trigger: true, params: { skip_download: true} }
    - { get: git-develop, trigger: true }
  - { put:  docker-image-go-vendor-develop, params: { build: git-develop} }
- name: build-go-vendor-master
  serial: true
  plan:
  - aggregate:
    - { get: docker-image-go-base-master, trigger: true, params: { skip_download: true} }
    - { get: git-master, trigger: true }
  - { put:  docker-image-go-vendor-master, params: { build: git-master} }